// Gauntlet of Far Reach
recipes.remove (<conarm:gauntlet_mat_reach>);
mods.jei.JEI.removeAndHide (<conarm:gauntlet_mat_reach>);
// Gauntlet (Base)
recipes.remove (<conarm:gauntlet_mat>);
mods.jei.JEI.removeAndHide (<conarm:gauntlet_mat>);
// Gauntlet of Power
recipes.remove (<conarm:gauntlet_mat_attack>);
mods.jei.JEI.removeAndHide (<conarm:gauntlet_mat_attack>);
// Gauntlet of Dexterity
recipes.remove (<conarm:gauntlet_mat_speed>);
mods.jei.JEI.removeAndHide (<conarm:gauntlet_mat_speed>);
// EFLN
recipes.remove (<tconstruct:throwball:1>);
mods.jei.JEI.removeAndHide (<tconstruct:throwball:1>);
// Shape Card all
recipes.remove (<rftools:shape_card>);
mods.jei.JEI.removeAndHide (<rftools:shape_card>);
recipes.remove (<rftools:shape_card:1>);
mods.jei.JEI.removeAndHide (<rftools:shape_card:1>);
recipes.remove (<rftools:shape_card:2>);
mods.jei.JEI.removeAndHide (<rftools:shape_card:2>);
recipes.remove (<rftools:shape_card:3>);
mods.jei.JEI.removeAndHide (<rftools:shape_card:3>);
recipes.remove (<rftools:shape_card:4>);
mods.jei.JEI.removeAndHide (<rftools:shape_card:4>);
recipes.remove (<rftools:shape_card:5>);
mods.jei.JEI.removeAndHide (<rftools:shape_card:5>);
recipes.remove (<rftools:shape_card:6>);
mods.jei.JEI.removeAndHide (<rftools:shape_card:6>);
recipes.remove (<rftools:shape_card:7>);
mods.jei.JEI.removeAndHide (<rftools:shape_card:7>);
recipes.remove (<rftools:shape_card:8>);
mods.jei.JEI.removeAndHide (<rftools:shape_card:8>);
recipes.remove (<rftools:shape_card:9>);
mods.jei.JEI.removeAndHide (<rftools:shape_card:9>);
recipes.remove (<rftools:shape_card:10>);
mods.jei.JEI.removeAndHide (<rftools:shape_card:10>);
//Traveller all
recipes.remove (<conarm:travel_sack>);
mods.jei.JEI.removeAndHide (<conarm:travel_sack>);
recipes.remove (<conarm:travel_belt>);
mods.jei.JEI.removeAndHide (<conarm:travel_belt>);
recipes.remove (<conarm:travel_potion>);
mods.jei.JEI.removeAndHide (<conarm:travel_potion>);
recipes.remove (<conarm:travel_night>);
mods.jei.JEI.removeAndHide (<conarm:travel_night>);
recipes.remove (<conarm:travel_goggles>);
mods.jei.JEI.removeAndHide (<conarm:travel_goggles>);
recipes.remove (<conarm:travel_soul>);
mods.jei.JEI.removeAndHide (<conarm:travel_soul>);
recipes.remove (<conarm:travel_slowfall>);
mods.jei.JEI.removeAndHide (<conarm:travel_slowfall>);
recipes.remove (<conarm:travel_sneak>);
mods.jei.JEI.removeAndHide (<conarm:travel_sneak>);
recipes.remove (<conarm:travel_belt_base>);
mods.jei.JEI.removeAndHide (<conarm:travel_belt_base>);
recipes.remove (<conarm:travel_goggles_base>);
mods.jei.JEI.removeAndHide (<conarm:travel_goggles_base>);
recipes.remove (<conarm:travel_cloak>);
mods.jei.JEI.removeAndHide (<conarm:travel_cloak>);
//Frosty Soles
recipes.remove (<conarm:frosty_soles>);
mods.jei.JEI.removeAndHide (<conarm:frosty_soles>);
// Actually Additions
recipes.remove (<actuallyadditions:block_directional_breaker>);
mods.jei.JEI.removeAndHide (<actuallyadditions:block_directional_breaker>);
recipes.remove (<actuallyadditions:block_phantom_breaker>);
mods.jei.JEI.removeAndHide (<actuallyadditions:block_phantom_breaker>);
recipes.remove (<actuallyadditions:block_phantom_placer>);
mods.jei.JEI.removeAndHide (<actuallyadditions:block_phantom_placer>);
recipes.remove (<actuallyadditions:block_placer>);
mods.jei.JEI.removeAndHide (<actuallyadditions:block_placer>);
recipes.remove (<actuallyadditions:block_fluid_placer>);
mods.jei.JEI.removeAndHide (<actuallyadditions:block_fluid_placer>);
recipes.remove (<actuallyadditions:block_breaker>);
mods.jei.JEI.removeAndHide (<actuallyadditions:block_breaker>);
recipes.remove (<actuallyadditions:item_spawner_changer>);
mods.jei.JEI.removeAndHide (<actuallyadditions:item_spawner_changer>);
// Avaritia
recipes.remove (<avaritia:infinity_bow>);
mods.jei.JEI.removeAndHide (<avaritia:infinity_bow>);
recipes.remove (<avaritia:endest_pearl>);
mods.jei.JEI.removeAndHide (<avaritia:endest_pearl>);
recipes.remove (<avaritia:infinity_shovel>);
mods.jei.JEI.removeAndHide (<avaritia:infinity_shovel>);
recipes.remove (<avaritia:infinity_pickaxe>.withTag({ench: [{lvl: 10 as short, id: 35 as short}]}));
mods.jei.JEI.removeAndHide (<avaritia:infinity_pickaxe>.withTag({ench: [{lvl: 10 as short, id: 35 as short}]}));
recipes.remove (<avaritia:infinity_axe>);
mods.jei.JEI.removeAndHide (<avaritia:infinity_axe>);
recipes.remove (<avaritia:infinity_hoe>);
mods.jei.JEI.removeAndHide (<avaritia:infinity_hoe>);
recipes.remove (<avaritia:neutronium_compressor>);
mods.jei.JEI.removeAndHide (<avaritia:neutronium_compressor>);
recipes.remove (<avaritia:compressed_crafting_table>);
mods.jei.JEI.removeAndHide (<avaritia:compressed_crafting_table>);
mods.avaritia.ExtremeCrafting.remove (<avaritia:neutronium_compressor>);
mods.jei.JEI.removeAndHide (<avaritia:neutronium_compressor>);
recipes.remove (<avaritia:extreme_crafting_table>);
mods.jei.JEI.removeAndHide (<avaritia:extreme_crafting_table>);
recipes.remove (<avaritia:double_compressed_crafting_table>);
mods.jei.JEI.removeAndHide (<avaritia:double_compressed_crafting_table>);
mods.avaritia.ExtremeCrafting.remove (<avaritia:endest_pearl>);
mods.jei.JEI.removeAndHide (<avaritia:endest_pearl>);
// Singularity Avaritia
mods.avaritia.Compressor.remove (<avaritia:singularity>);
mods.jei.JEI.removeAndHide (<avaritia:singularity>);
mods.avaritia.Compressor.remove (<avaritia:singularity:1>);
mods.jei.JEI.removeAndHide (<avaritia:singularity:1>);
mods.avaritia.Compressor.remove (<avaritia:singularity:2>);
mods.jei.JEI.removeAndHide (<avaritia:singularity:2>);
mods.avaritia.Compressor.remove (<avaritia:singularity:3>);
mods.jei.JEI.removeAndHide (<avaritia:singularity:3>);
mods.avaritia.Compressor.remove (<avaritia:singularity:4>);
mods.jei.JEI.removeAndHide (<avaritia:singularity:4>);
mods.avaritia.Compressor.remove (<avaritia:singularity:5>);
mods.jei.JEI.removeAndHide (<avaritia:singularity:5>);
mods.avaritia.Compressor.remove (<avaritia:singularity:6>);
mods.jei.JEI.removeAndHide (<avaritia:singularity:6>);
mods.avaritia.Compressor.remove (<avaritia:singularity:7>);
mods.jei.JEI.removeAndHide (<avaritia:singularity:7>);
mods.avaritia.Compressor.remove (<avaritia:singularity:8>);
mods.jei.JEI.removeAndHide (<avaritia:singularity:8>);
mods.avaritia.Compressor.remove (<avaritia:singularity:9>);
mods.jei.JEI.removeAndHide (<avaritia:singularity:9>);
mods.avaritia.Compressor.remove (<avaritia:singularity:10>);
mods.jei.JEI.removeAndHide (<avaritia:singularity:10>);
mods.avaritia.Compressor.remove (<avaritia:singularity:11>);
mods.jei.JEI.removeAndHide (<avaritia:singularity:11>);
mods.avaritia.Compressor.remove (<avaritia:singularity:12>);
mods.jei.JEI.removeAndHide (<avaritia:singularity:12>);
mods.avaritia.Compressor.remove (<avaritia:singularity:13>);
mods.jei.JEI.removeAndHide (<avaritia:singularity:13>);
mods.avaritia.Compressor.remove (<avaritia:singularity:14>);
mods.jei.JEI.removeAndHide (<avaritia:singularity:14>);
// Extra Utils2
recipes.remove (<extrautils2:teleporter:1>);
mods.jei.JEI.removeAndHide (<extrautils2:teleporter:1>);
recipes.remove (<extrautils2:teleporter>);
mods.jei.JEI.removeAndHide (<extrautils2:teleporter>);
recipes.remove (<extrautils2:playerchest>);
mods.jei.JEI.removeAndHide (<extrautils2:playerchest>);
recipes.remove (<actuallyadditions:item_bag>);
mods.jei.JEI.removeAndHide (<actuallyadditions:item_bag>);
recipes.remove (<actuallyadditions:item_void_bag>);
mods.jei.JEI.removeAndHide (<actuallyadditions:item_void_bag>);
recipes.remove (<extrautils2:itemdestructionwand>);
mods.jei.JEI.removeAndHide (<extrautils2:itemdestructionwand>);
recipes.remove (<extrautils2:chunkloader>);
mods.jei.JEI.removeAndHide (<extrautils2:chunkloader>);
recipes.remove (<actuallyadditions:item_leaf_blower_advanced>);
mods.jei.JEI.removeAndHide (<actuallyadditions:item_leaf_blower_advanced>);
recipes.remove (<extrautils2:poweroverload>);
mods.jei.JEI.removeAndHide (<extrautils2:poweroverload>);
// Mekanism
recipes.remove (<mekanism:anchorupgrade>);
mods.jei.JEI.removeAndHide (<mekanism:anchorupgrade>);
recipes.remove (<mekanism:robit>);
mods.jei.JEI.removeAndHide (<mekanism:robit>);
recipes.remove (<mekanism:obsidiantnt>);
mods.jei.JEI.removeAndHide (<mekanism:obsidiantnt>);
recipes.remove (<mekanism:cardboardbox>);
mods.jei.JEI.removeAndHide (<mekanism:cardboardbox>);
recipes.remove (<mekanism:basicblock:6>.withTag({tier: 0}));
mods.jei.JEI.removeAndHide (<mekanism:basicblock:6>.withTag({tier: 0}));
recipes.remove (<mekanism:basicblock:6>.withTag({tier: 1}));
mods.jei.JEI.removeAndHide (<mekanism:basicblock:6>.withTag({tier: 1}));
recipes.remove (<mekanism:basicblock:6>.withTag({tier: 2}));
mods.jei.JEI.removeAndHide (<mekanism:basicblock:6>.withTag({tier: 2}));
recipes.remove (<mekanism:basicblock:6>.withTag({tier: 3}));
mods.jei.JEI.removeAndHide (<mekanism:basicblock:6>.withTag({tier: 3}));
recipes.remove (<mekanism:machineblock:13>);
mods.jei.JEI.removeAndHide (<mekanism:machineblock:13>);
recipes.remove (<mekanism:basicblock2>);
mods.jei.JEI.removeAndHide (<mekanism:basicblock2>);
recipes.remove (<mekanism:basicblock:15>);
mods.jei.JEI.removeAndHide (<mekanism:basicblock:15>);
recipes.remove (<mekanism:basicblock:14>);
mods.jei.JEI.removeAndHide (<mekanism:basicblock:14>);
// Draconic
recipes.remove (<draconicevolution:celestial_manipulator>);
mods.jei.JEI.removeAndHide (<draconicevolution:celestial_manipulator>);
mods.jei.JEI.removeAndHide (<draconicevolution:reactor_core>);
recipes.remove (<draconicadditions:chaos_stabilizer_core>);
mods.jei.JEI.removeAndHide (<draconicadditions:chaos_stabilizer_core>);
recipes.remove (<draconicevolution:reactor_part>);
mods.jei.JEI.removeAndHide (<draconicevolution:reactor_part>);
recipes.remove (<draconicevolution:dislocator_pedestal>);
mods.jei.JEI.removeAndHide (<draconicevolution:dislocator_pedestal>);
recipes.remove (<draconicevolution:reactor_component>);
mods.jei.JEI.removeAndHide (<draconicevolution:reactor_component>);
recipes.remove (<draconicevolution:reactor_component:1>);
mods.jei.JEI.removeAndHide (<draconicevolution:reactor_component:1>);
recipes.remove (<draconicevolution:draconic_spawner>);
mods.jei.JEI.removeAndHide (<draconicevolution:draconic_spawner>);
mods.jei.JEI.removeAndHide (<draconicevolution:draconium_chest>);
//Draconic Dust
recipes.remove (<draconicevolution:draconium_dust>);
// Thermal Expansion
recipes.remove (<thermalexpansion:florb>);
mods.jei.JEI.removeAndHide (<thermalexpansion:florb>);
recipes.remove (<thermalexpansion:satchel:100>.withTag({Accessible: 1 as byte}));
mods.jei.JEI.removeAndHide (<thermalexpansion:satchel:100>.withTag({Accessible: 1 as byte}));
recipes.remove (<thermalexpansion:satchel:4>.withTag({Accessible: 1 as byte}));
mods.jei.JEI.removeAndHide (<thermalexpansion:satchel:4>.withTag({Accessible: 1 as byte}));
recipes.remove (<thermalexpansion:satchel:3>.withTag({Accessible: 1 as byte}));
mods.jei.JEI.removeAndHide (<thermalexpansion:satchel:3>.withTag({Accessible: 1 as byte}));
recipes.remove (<thermalexpansion:satchel:2>.withTag({Accessible: 1 as byte}));
mods.jei.JEI.removeAndHide (<thermalexpansion:satchel:2>.withTag({Accessible: 1 as byte}));
recipes.remove (<thermalexpansion:satchel:1>.withTag({Accessible: 1 as byte}));
mods.jei.JEI.removeAndHide (<thermalexpansion:satchel:1>.withTag({Accessible: 1 as byte}));
recipes.remove (<thermalexpansion:satchel>.withTag({Accessible: 1 as byte}));
mods.jei.JEI.removeAndHide (<thermalexpansion:satchel>.withTag({Accessible: 1 as byte}));
// EnderIO
recipes.remove (<enderio:block_concussion_charge>);
mods.jei.JEI.removeAndHide (<enderio:block_concussion_charge>);
recipes.remove (<enderio:block_ender_charge>);
mods.jei.JEI.removeAndHide (<enderio:block_ender_charge>);
recipes.remove (<enderio:block_confusion_charge>);
mods.jei.JEI.removeAndHide (<enderio:block_confusion_charge>);
recipes.remove (<enderio:block_inventory_panel_sensor>);
mods.jei.JEI.removeAndHide (<enderio:block_inventory_panel_sensor>);
// Tech Reborn
recipes.remove (<techreborn:chunk_loader>);
mods.jei.JEI.removeAndHide (<techreborn:chunk_loader>);
// RF Tools
recipes.remove (<rftools:spawner>);
mods.jei.JEI.removeAndHide (<rftools:spawner>);
// Industrial Craft 2
recipes.remove (<ic2:te:2>);
mods.jei.JEI.removeAndHide (<ic2:te:2>);
recipes.remove (<ic2:te:82>);
mods.jei.JEI.removeAndHide (<ic2:te:82>);
recipes.remove (<ic2:te:1>);
mods.jei.JEI.removeAndHide (<ic2:te:1>);
// Applied Energistics 2
recipes.remove (<appliedenergistics2:part:300>);
mods.jei.JEI.removeAndHide (<appliedenergistics2:part:300>);
recipes.remove (<appliedenergistics2:part:302>);
mods.jei.JEI.removeAndHide (<appliedenergistics2:part:302>);
// Banidos
recipes.remove (<minecraft:boat>);
mods.jei.JEI.removeAndHide (<minecraft:boat>);
recipes.remove (<minecraft:dark_oak_boat>);
mods.jei.JEI.removeAndHide (<minecraft:dark_oak_boat>);
recipes.remove (<minecraft:acacia_boat>);
mods.jei.JEI.removeAndHide (<minecraft:acacia_boat>);
recipes.remove (<minecraft:jungle_boat>);
mods.jei.JEI.removeAndHide (<minecraft:jungle_boat>);
recipes.remove (<minecraft:birch_boat>);
mods.jei.JEI.removeAndHide (<minecraft:birch_boat>);
recipes.remove (<minecraft:spruce_boat>);
mods.jei.JEI.removeAndHide (<minecraft:spruce_boat>);
recipes.remove (<minecraft:item_frame>);
mods.jei.JEI.removeAndHide (<minecraft:item_frame>);
recipes.remove (<minecraft:hopper_minecart>);
mods.jei.JEI.removeAndHide (<minecraft:hopper_minecart>);
recipes.remove (<minecraft:minecart>);
mods.jei.JEI.removeAndHide (<minecraft:minecart>);
recipes.remove (<minecraft:furnace_minecart>);
mods.jei.JEI.removeAndHide (<minecraft:furnace_minecart>);
recipes.remove (<minecraft:chest_minecart>);
mods.jei.JEI.removeAndHide (<minecraft:chest_minecart>);
recipes.remove (<minecraft:tnt_minecart>);
mods.jei.JEI.removeAndHide (<minecraft:tnt_minecart>);
recipes.remove (<minecraft:dropper>);
mods.jei.JEI.removeAndHide (<minecraft:dropper>);
recipes.remove (<minecraft:dispenser>);
mods.jei.JEI.removeAndHide (<minecraft:dispenser>);
recipes.remove (<ic2:boat:3>);
mods.jei.JEI.removeAndHide (<ic2:boat:3>);
recipes.remove (<minecraft:observer>);
mods.jei.JEI.removeAndHide (<minecraft:observer>);

recipes.remove (<actuallyadditions:block_miner>);
mods.jei.JEI.removeAndHide (<actuallyadditions:block_miner>);
recipes.remove (<rftools:storage_scanner>);
mods.jei.JEI.removeAndHide (<rftools:storage_scanner>);
recipes.remove (<enderio:item_dark_steel_upgrade:1>.withTag({"enderio:dsu": "enderio:inv"}));
mods.jei.JEI.removeAndHide (<enderio:item_dark_steel_upgrade:1>.withTag({"enderio:dsu": "enderio:inv"}));
recipes.remove (<enderio:item_dark_steel_upgrade:1>.withTag({"enderio:dsu": "enderio:inv1"}));
mods.jei.JEI.removeAndHide (<enderio:item_dark_steel_upgrade:1>.withTag({"enderio:dsu": "enderio:inv1"}));
recipes.remove (<enderio:item_dark_steel_upgrade:1>.withTag({"enderio:dsu": "enderio:inv2"}));
mods.jei.JEI.removeAndHide (<enderio:item_dark_steel_upgrade:1>.withTag({"enderio:dsu": "enderio:inv2"}));
// Vajra
recipes.remove (<gravisuite:vajra:26>);
recipes.remove (<gravisuite:vajra>.withTag({charge: 1.0E7}));
// Tanks do meka
recipes.remove (<mekanism:machineblock2:11>.withTag({tier: 0}));
recipes.remove (<mekanism:machineblock2:11>.withTag({tier: 1}));
recipes.remove (<mekanism:machineblock2:11>.withTag({tier: 2}));
recipes.remove (<mekanism:machineblock2:11>.withTag({tier: 3}));